
pages = ['defense_byTKL.html',
'kicking_byPOINTS.html',
'passing_byPASS_YDS.html',
'punting_byYDS_PER_PUNT.html',
'receiving_byRECPT_YDS.html',
'returns_byOPP_PUNT_YD_AVG.html',
'rushing_byRUSH_YDS.html']

seasons = ['2008', '2009', '2010', '2011', '2012']

teams = ['buffalo-bills',
'miami-dolphins',
'new-york-jets',
'new-england-patriots',
'dallas-cowboys',
'philadelphia-eagles',
'new-york-giants',
'washington-redskins',
'cincinnati-bengals',
'cleveland-browns',
'baltimore-ravens',
'pittsburgh-steelers',
'chicago-bears',
'detroit-lions',
'green-bay-packers',
'minnesota-vikings',
'indianapolis-colts',
'jacksonville-jaguars',
'houston-texans',
'tennessee-titans',
'tampa-bay-buccaneers',
'atlanta-falcons',
'carolina-panthers',
'new-orleans-saints',
'denver-broncos',
'san-diego-chargers',
'kansas-city-chiefs',
'oakland-raiders',
'san-francisco-49ers',
'arizona-cardinals',
'st-louis-rams',
'seattle-seahawks']
